pipeline{
    agent any

    parameters{
        string(
            name:'APP_PORT',
            defaultValue:'3000',
            description:'Server Port'
        )
    }

    environment{
        IMAGE_NAME='jenkins-demo-app'
    }

    stages{
        stage('Checkout'){
            steps{
                echo 'Checking out Source Code FromGit Repo'
                checkout scm
            }
        }
        stage('Check Dcker'){
            steps{
                bat 'docker --version'
            }
        }
        stage('Dependencies') {
    steps {
        dir('JenkinsFileDemo') {
            bat 'npm install'
        }
    }
}
 stage('Test APP') {
    steps {
        dir('JenkinsFileDemo') {
            bat 'npm test'
        }
    }
}
        stage('Build'){
            steps{
                dir('JenkinsFileDemo') {
    bat 'docker build -t sampleapp:1.0.'
}
            }
        }
        stage('Run Container'){
            steps{
                bat '''
                    docker run -d --name node-app-%BUILD_NUMBER% -p %APP_PORT%:3000 %IMAGE_NAME%:%BUILD_NUMBER%
                    '''
            }
        }
        stage('Verify'){
            steps{
                bat '''
                    echo App Deployed Successfully
                    echo Open http://localhost:%APP_PORT%
                    docker ps
                    '''
            }
        }

    }
}